In [ ]:
#Numpy - Numeric python
#Most powerful package - Library
#Numpy - Dimensions
#A - One dimensional array
#[A,B] || [A,B] - Two dimensional array - Row || Column
#Three dimensional
#Array - storing, ,manuplating, similar data type
#Faster than any mathematical functions
#Convinient compared to other packages
#Memory efficiency
#supports multi dimensinal arrays
#speed(numpy operations)>speed(list operations)
#size(numpy operations)memory optimization(list operations)

import numpy as np

In [4]:
#create a numpy array
#1D - array

arr1D=np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [ ]:
#creating a 2D array

arr2D=np.array([[1,2,3],[4,5,6]])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [ ]:
#creating array with default values
# here the first 2 denotes 2 dimesional array ,3 denotes number of 0 
# in place of zeros we can also write ones(only)

allZeroes=np.zeros((2,3))
print(allZeroes)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
#creating array with all values of element as '1'
allOnes=np.ones((2,3))
print(allOnes)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#creating matrix with all valiues of element as 'constant values-n-full values'

# here the first 2 denotes 2 dimesional array ,3 denotes number of 6, and 6 denotes the number 6

allConstant=np.full((2,3),6)
print(allConstant)

[[6 6 6]
 [6 6 6]]


In [ ]:
#creating identity matrix - 1
# 4 denotes 4 dimensional array
# eye denotes identity matrix

identityMatrix=np.eye(4)
print(identityMatrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#creating random matrices
#here 3,3 denotes 3X3 matrix and by defaultly it takes the values between 0 and 1
# basically rand function be used in numpy 

rand1=np.random.rand(3,3)
print(rand1)

#Between 10 and 20
#3,4 denotes 3x4
# in randint lowerbound is inclusive so 10 can also be printed

rand2=np.random.randint(10,20,(3,4))
print(rand2)

[[0.25276949 0.81244419 0.91004722]
 [0.44745851 0.63485685 0.87415072]
 [0.36221686 0.47652564 0.44524505]]
[[16 15 11 16]
 [11 17 11 17]
 [12 19 15 16]]


In [ ]:
#To generate random numbers between a and b, you can use:
#rand1 = (b - a) * np.random.rand(3, 3) + a [using rand function only] 

rand2=2*np.random.rand(3,4)-1
print(rand2)

[[-0.93702047 -0.9676285   0.08364575 -0.72472379]
 [-0.0741757  -0.08326904 -0.09391494  0.26551437]
 [ 0.8136637   0.2542402  -0.60632918  0.138904  ]]


In [ ]:
#Array properties
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

#Shape of array - prints nXm matrices
print(f'Th shape of array is{arr.shape}')

#Size of array - prints number of elements in array
print(f'The size of array is{arr.size}')

#DataType of array
print(f'The type of array is{arr.dtype}')

#Dimensions of array
print(f'The dimensions of array is{arr.ndim}')

[[1 2 3]
 [4 5 6]]
Th shape of array is(2, 3)
The size of array is6
The type of array isint64
The dimensions of array is2


In [ ]:
#Indexing and Slicing

#access the element in 1D array
arr=np.array([1,2,3])
print(arr)
# prints second element in array with index 1
print(arr[1])

#slicing the elements
print(arr[2:3])

#access the element in 2D array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2[1,1])
print(arr2[0:1])
print(arr2[1:0])

[1 2 3]
2
[3]
[[1 2 3]
 [4 5 6]]
5
[[1 2 3]]
[]


In [ ]:
#l1=[]
#l1.append(_) for _ in range[10]
# arranging elements in list between a range in numpy instead of append()

l1=np.arange(0,10)

print(l1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# maths fundamentals with numpy

a=np.array([1,2,3])
b=np.array([3,4,5])
print(f'The sum of a and b is{a+b}')
print(f'The difference of a and b is{a-b}')
print(f'The product of a and b is{a*b}')
print(f'The division of a and b is{a/b}')

The sum of a and b is[4 6 8]
The difference of a and b is[-2 -2 -2]
The product of a and b is[ 3  8 15]
The division of a and b is[0.33333333 0.5        0.6       ]


In [ ]:
#Matrix multiplication
b1=np.array([[1,2,3],[2,3,4]]) # 2X3 matrix
b2=np.array([[5,6],[7,8],[1,3]]) # 3X2 matrix
c=np.dot(b1,b2) # dot() performs matrix multiplication in numpy
print(c)

[[22 31]
 [35 48]]


In [34]:
b2

array([[5, 6],
       [7, 8],
       [1, 3]])

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])

# finding datatype
type(arr)

numpy.ndarray

In [ ]:
#Dot product - mxn || nxp
arr1=np.eye(2) # 2D array 
print(arr1)

[[1. 0.]
 [0. 1.]]


In [37]:
arr1.shape

(2, 2)

In [38]:
result=np.dot(arr1,arr)
print(result)

[[1. 2. 3.]
 [4. 5. 6.]]


In [39]:
r2=np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
t1=np.random.randint(3,6,(3,3))
t2=np.random.randint(3,6,(3,3))
t1

array([[5, 5, 4],
       [3, 4, 3],
       [3, 3, 3]], dtype=int32)

In [51]:
t2

array([[4, 5, 5],
       [4, 5, 4],
       [5, 3, 5]], dtype=int32)

In [41]:
#statistical operations
mean=t2.mean()
max=t2.max()
median=np.median(t2)
std=np.std(t2)
var=np.var(t2)

In [ ]:
# to get one cell of code execution in only one cell use print for every variable instead of executing each variable in new cell

print(mean)
print(median)
print(max)
print(std)
print(var)
print(std*std)

3.5555555555555554
4.0
4
0.49690399499995325
0.24691358024691354
0.24691358024691357


In [ ]:
#Trignometric functions
#sin(x),cos(x),tan(x),cot(x),cosec(x),sec(x)

angles=np.array([0,15,30,45,60,75,90])
result=np.sin(np.radians(angles))
result1=np.cos(np.radians(angles))
result2=np.tan(np.radians(angles))

In [60]:
print(angles)
print(result)
print(result1)
print(result2)

[ 0 15 30 45 60 75 90]
[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [61]:
arr=np.array([1,2,3,4,5,6])
#Reshape the array
reshapearr=arr.reshape(2,3)
print(reshapearr)
#to convert/flatten any n dim array
flattenedarr=arr.flatten()
print(flattenedarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [62]:
#stacking the data
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])

#vertical stacking
arr3=np.vstack((arr1,arr2))
print(f"The shape of arr3 isd {arr3.shape}")
print(arr3)

#horizontal stacking
arr4=np.hstack((arr1,arr2))
print(f"The shape of arr3 is {arr3.shape}")
print(arr4)

The shape of arr3 isd (2, 4)
[[ 1  2  3  4]
 [10 20 30 40]]
The shape of arr3 is (2, 4)
[ 1  2  3  4 10 20 30 40]


In [63]:
#filtering
arr=np.array([10,20,30,40,50,60,70,80])

farr=arr[arr>40]
print(farr)

[50 60 70 80]
